### ISSUE TITLE
CHANGE: Item Parent Check box

### ISSUE THREAD

**Issue by thansen** [scottdkey/whiskey-night#10]
![Screen Shot 2020-05-30 at 3 04 50 PM](https://user-images.githubusercontent.com/2190796/83339011-eb95c580-a286-11ea-944f-f89543684e1f.png)

We should probably change it so that when a CHILD INGREDIENT is checked, then the PARENT ITEM check box simply disappears and is un-checkable. 
If the Parent is checked  we can auto check all the children and add the name to all the cells.

**Comment by scottdkey** [comment]
Added my own approach to this. We should chat about it to see which direction to go. 

Right now if all children are checked the top box is checked. If certain things have been checked off and you check at top level it adds your name to remaining(unclaimed) items.

**Comment by thansen** [comment]
That sounds fine to me, nice.
