### ISSUE TITLE
Modal Header style fixes

### ISSUE THREAD

**Issue by thansen** [scottdkey/whiskey-night#5]
![Screen Shot 2020-05-30 at 2 48 20 PM](https://user-images.githubusercontent.com/2190796/83338772-aa041b00-a284-11ea-86e3-c3b7f93a492c.png)
![Screen Shot 2020-05-30 at 2 48 14 PM](https://user-images.githubusercontent.com/2190796/83338773-ad97a200-a284-11ea-9108-abacf02e7531.png)

The styling isn't quite right on modal headers. The horizontal rule is too thick and the X is too small. This might be because you aren't using the text from the font. Maybe you are using some sort of generic icon?

I've added an icon to the images folder for you to use incase its easier.

**Comment by scottdkey** [comment]
Looks like the issue was coming from the Unicode character having different font weights than intended. Implemented the svg. Fixes in place
